### ISSUE TITLE
Can't show popup window completely on Arch linux KDE

### ISSUE THREAD

**Issue by kktt007** [Pitmairen/selection-search#102]
Arch Linux KDE
Browser: Vivaldi v3.3

Image one is the word near the top of a website,SS can't show the other option above.

Image two is the word in the middle of  a website, SS also can't show the option completely. But we could scoll the side bar to the top so the hidden options could be shown. Just like Image three. Notice the red line.

Blow image is for reference. So i think if we could make the options be shown to two or three column(customized feature). So that all the option could be shown complete. Maybe there're better ways(Although kde is not so good but i keep using linux). 

Many  many thanks. Pitmairen.

- Image one:

<img width="790" alt="ss4" src="https://user-images.githubusercontent.com/7880005/92719122-4914d480-f395-11ea-8c59-3247f959d9dd.png">

- Image two and three

<img width="804" alt="ss2" src="https://user-images.githubusercontent.com/7880005/92719040-326e7d80-f395-11ea-8aa9-34e2f6eb4e2b.png">

<img width="786" alt="ss3" src="https://user-images.githubusercontent.com/7880005/92719083-3ac6b880-f395-11ea-9b35-15bc1b3f2d6d.png">

**Comment by Pitmairen** [comment]
Arch + KDE is great, I have used it myself for many years. :)

There is some logic that tries to place the popup inside the window if it opens outside of the view. I can probably improve it a little bit, by preferring the direction that has more scroll space left. But it can still fail if the screen is small and the popup is longer than the page.

It is possible to tweak the popup styling by using custom css. For example, try to paste the following into the textarea that opens if you click:
Options page -> Popup menu -> Advanced settings -> Customize 

```css
.mainmenu > li:first-child, .mainmenu input{
 width: 100%;
 box-sizing: border-box;
}
.mainmenu > li{
  display: inline-block;
}
.mainmenu {
 width: 440px;
}
```
This should arrange the search engines into multiple columns. You can tweak the last `width` value to change the number of columns. (This assumes that you are starting from the default style, with an empty textarea)

I only tested it in Chrome, but I think it should work the same in Vivaldi.

**Comment by kktt007** [comment]
unbelievable, you are the man. 厉害

May i kown your blog or other websites?  Because i want to use  more good extensions or software you use. Learning from you, . SS is my no.1 extension. 

Many many thanks. Pitmairen

<img width="639" alt="ss" src="https://user-images.githubusercontent.com/7880005/92928725-17be0680-f472-11ea-8bac-7acb0d36c563.png">

**Comment by Pitmairen** [comment]
Looks great :+1: 

Most of my code is available here on github, it is mostly just various hobby projects. Though I haven't had that much time for new development lately so you won't find that much new exiting stuff.
