### ISSUE TITLE
How to change the size of the icon.

### ISSUE THREAD

**Issue by kktt007** [Pitmairen/selection-search#103]
Thanks for helping  me solve a lot. #102 #101 . I decide to use only icon because it will save more time. Thanks. Pitmairen.

Now another issue is how to change the size of the icon. It seems too small. In a words, so many thanks. My author.

![2020-09-12_](https://user-images.githubusercontent.com/7880005/92988493-a7a99200-f4fe-11ea-90cb-72e747dbbac8.png)

**Comment by Pitmairen** [comment]
You can change the icon size using this: 
```css
.popup img{
 zoom: 1.5;
}
```
Or an alternative is this:
```css
.popup img{
 transform: scale(1.5);
}
```
Both will increase the size of the icons, but they differ in how they affects the other elements. So you have to test what works best for you, and just tweak the number to get the desired size.

But most of the icons are fetched from the site's favicon, which is often just a 16x16 icon. So the quality will probably not be that great if you increase the size too much. It can be fixed though by adding custom icon url to use higher quality icons.
  

You can also change the size of the clickable area around the icon by tweaking the following value:
```css
.popup a{
 padding: 0.5em;
}
```

**Comment by kktt007** [comment]
Wonderful. It works well with below. Thanks our excellent author. 
.popup img{
 zoom: 1.5;
}

.popup a{
 padding: 0.5em;
}
