### ISSUE TITLE
the icon seems not display for several months

### ISSUE THREAD

**Issue by kktt007** [Pitmairen/selection-search#109]
I have use https://api.faviconkit.com/google.com/ instead of the default way. The default seems not display. I changed most defaults now. But this one "CURRENT_DOMAIN": I couldn't find a way to change it's icon. Plz fix the icon source or give me a tip to get icon from "https://api.faviconkit.com/" for "CURRENT_DOMAIN"
Thanks again. My author.

**Comment by Pitmairen** [comment]
The default url is currently https://s2.googleusercontent.com/s2/favicons?domain_url=google.com

Does this not work for you? Can you give an example of a domain url that is not working?

**Comment by kktt007** [comment]
Good day. My author,

https://www.merriam-webster.com/dictionary/apple
https://www.antonym.com/synonyms/apple
https://www.collinsdictionary.com/dictionary/english/apple
https://www.niftyword.com/dictionary/apple/

And  "CURRENT_DOMAIN" related to above url will not display

Below image for ref.
https://img.vim-cn.com/c7/66bce0d86dcad81f5537c91d17827020a436a9.jpg

**Comment by Pitmairen** [comment]
Ok, I see. I will check to see if it is possible to create a fallback solution that tries to load the icons from multiple different sources.

**Comment by Pitmairen** [comment]
I have added support for loading icons from multiple sources. It will now try  api.faviconkit.com if the other one fails. 

It will be included in the next release.

**Comment by kktt007** [comment]
> I have added support for loading icons from multiple sources. It will now try api.faviconkit.com if the other one fails.
> 
> It will be included in the next release.

Many thanks to your excellent work. Pitmairen. Vivaldi and select search is very important for my life.  Should i close this top?

**Comment by Pitmairen** [comment]
I guess we can just close it, and then open it again if it's not working.
