### ISSUE TITLE
Search "popup" alignment gets distorted, if the selection is on the far right/left.

### ISSUE THREAD

**Issue by ghost** [Pitmairen/selection-search#11]
![3](https://cloud.githubusercontent.com/assets/8393129/7787431/f3eecacc-020b-11e5-88c3-548a2de18894.png)
as opposed to this ..
![untitled1](https://cloud.githubusercontent.com/assets/8393129/7787432/fbf008b2-020b-11e5-8d97-54a2c9487f78.png)
It used to maintain its alignment in earlier versions.

**Comment by Pitmairen** [comment]
Add this to the style:
```
.popup{
    white-space: nowrap;
}
```

**Comment by Droyk** [comment]
Just checked it.
 it is fixed [Pitmairen](https://github.com/Pitmairen) plz close this
