### ISSUE TITLE
New feature: opening multiple search engines once a time

### ISSUE THREAD

**Issue by kktt007** [Pitmairen/selection-search#113]
First, thanks soooo much. Pitmairen. Selection search saving lots of my time in looking up "english word".

I just buy a IPAD used for reading english book. So i met too many new words. A new mind come to my mind just now. Could "Selection-search" open multiple urls once in a time. 

E.g. I am looking up a new word "illustrate", normally below fixed four websites could help me master a new word: 
1. https://www.merriam-webster.com/dictionary/illustrate
2. https://dictionary.cambridge.org/us/dictionary/english/illustrate
3. https://www.ldoceonline.com/dictionary/illustrate
4. https://www.oxfordlearnersdictionaries.com/definition/english/illustrate?q=illustrate

I think this feature will let selection search be a toppest productive extenstion. 

Too many websites now! hahaha, bacause i am a heavy user of Selection-search.

![selection-search](https://img.vim-cn.com/fa/37d6fd1c73c1ef716594cbc25267d210617227.png)

**Comment by Pitmairen** [comment]
Have you tried using a sub menu with the open all on click option enabled?

Add a new sub menu using the "Add New Submenu" button. Then drag the searches you want into the sub menu.  
If you click the wrench next to the sub menu you can enable the "Open all on click" option. 

Now if you click on the sub menu, all the search engines in the sub menu should open with the same search query.

**Comment by kktt007** [comment]
> Have you tried using a sub menu with the open all on click option enabled?
> 
> Add a new sub menu using the "Add New Submenu" button. Then drag the searches you want into the sub menu.
> If you click the wrench next to the sub menu you can enable the "Open all on click" option.
> 
> Now if you click on the sub menu, all the search engines in the sub menu should open with the same search query.

It works perfectly. Thanks my author.
