### ISSUE TITLE
Mycroft Project support dropped?

### ISSUE THREAD

**Issue by moongoses** [Pitmairen/selection-search#114]
Hello.
I just found out that there is not anymore possible to add search engines from Mycroft project page.
What is the reason behind this and is there a possibility for restoring the support for selection-search on Mycroft?

If not, that this option should be removed from Selection search.

**Comment by Pitmairen** [comment]
Thanks for letting me know. Looks like mycroft have done some small changes to the layout on their web pages, so the selection search integration broke.

I have created a fix to make it work again and it will be included in the next release.

**Comment by moongoses** [comment]
Great news. Hope that next release will be soon.

**Comment by Pitmairen** [comment]
I have submitted a new release to the web store now. It has to be reviewed by Google before it gets published, hopefully it doesn't take too long.

**Comment by moongoses** [comment]
It is published. Excellent job Pitmarien.
Thanks for your prompt support and excellent extension,

**Comment by moongoses** [comment]
Hello.
It seems that Mycroft integration is broken again.
Thx
    On Saturday, March 20, 2021, 10:36:43 PM GMT+1, Per ***@***.***> wrote:  
 
 


I have submitted a new release to the web store now. It has to be reviewed by Google before it gets published, hopefully it doesn't take too long.

**Comment by Pitmairen** [comment]
It still works for me. What browser are you using?

**Comment by moongoses** [comment]
I'm using Vivaldi as my main browser, currently on latest snapshot.
But you are right, it's browser related.
I've just checked with another browser (Opera) and the stable version of Vivaldi, no issues in both of them.So it is something broken in the snapshot stream.

Sorry for bothering you.
    On Sunday, January 23, 2022, 05:35:27 PM GMT+1, Per ***@***.***> wrote:  
 
 


It still works for me. What browser are you using?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pitmairen** [comment]
yeah, I checked the stable Vivaldi version and it seems to be working fine.

**Comment by moongoses** [comment]
Hi,
This is what I've discovered, maybe you can have some use of it.
In the browser's extension setting, I checked the option for extension to be available in the private (incognito) mode.After that the icon showed up on mycroft page.
After this if I restore the setting to off, it still works but until the restart of the browser. It the setting is left enabled, no issues.
I've also tried with disabling the extension and reenabling, but without effect.
Only option for enabling extension in the incognito solves it.
Pretty weird, ain't it?
Take care.
    On Monday, January 24, 2022, 04:19:41 PM GMT+1, Per ***@***.***> wrote:  
 
 


yeah, I checked the stable Vivaldi version and it seems to be working fine.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dante3732** [comment]
> In the browser's extension setting, I checked the option for extension to be available in the private (incognito) mode.After that the icon showed up on mycroft page.

Thanks it help me. 👌
