### ISSUE TITLE
Is there a way to maintain the popup direction in pages with different language?

### ISSUE THREAD

**Issue by ghost** [Pitmairen/selection-search#12]
This is how it appears in English..
![untitled1](https://cloud.githubusercontent.com/assets/8393129/7787442/9b216796-020c-11e5-9e84-ec0754b75fdb.png)
sometimes it reverses the direction, in pages with different languages.
i.e.
![untitled](https://cloud.githubusercontent.com/assets/8393129/7787448/c937b432-020c-11e5-9746-874f4d0a4e18.png)
Can the direction be maintained in such pages?

**Comment by Pitmairen** [comment]
It can probably be done by adding this to the style:
```
.popup{
    direction: ltr;
}
```

ltr: left to right
rtl: right to left

**Comment by bugreport0** [comment]
Thanks a lot.

**Comment by Droyk** [comment]
Thnanxx for the solution i was finding this too thanxxx .made my day .............and plz close this issue down
