### ISSUE TITLE
"Failed to load synced settings (An unexpected error occurred)" with sync turned off

### ISSUE THREAD

**Issue by eMPee584** [Pitmairen/selection-search#121]
We want to deploy firefox preloaded with 💚 selection-search and this config: https://github.com/fsfw-dresden/usb-live-linux/blob/master/features/config_firefox_selection_search_schulstick/user-config/.mozilla/firefox/fsfw1234.default/browser-extension-data/selection-search%40myr1.net/storage.js

But even though all sync options are turned off, this **Synchronization Error** keeps coming up:
![image](https://user-images.githubusercontent.com/1227833/165600140-1d99ed34-bc03-45b5-bb8e-0feb3aaee00c.png)

What could be done to suppress this?
I checked the addon's storage.js when this happens and the only difference to the linked file is a version bump and minification..

**Comment by Pitmairen** [comment]
Hmm, I'm not sure why you get this error. It seems to be the call to `storage.sync.get` that is failing. This is always called even if the sync settings are turned off.

I have not seen this problem before. I believe that the usual behavior if the browser does not support setting sync, is that the storage.sync api will just behave as a local storage and the call should not fail. 

I'm note sure how this preloading works, but if the install is different from the normal install maybe something is missing. There are some notes on this page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync

> Note that the implementation of storage.sync in Firefox relies on the Add-on ID. If you use storage.sync, you must set an ID for your extension using the [browser_specific_settings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) manifest.json key.

What version of firefox are you using?

**Comment by eMPee584** [comment]
The preloading basically works by assembling a lean skeleton profile with the extensions xpis and storage jsons.. also global preferences and policies assembled from individual JSON files at build time.. here's the final assembly as it gets included into the squashfs: http://empeebase.ydns.eu/zeug/firefox-preloaded.tar.xz
Firefox at version `91.8.0esr-1~deb11u1` but i've had this error occasionally since about a year on older versions, too.. hoped it would go away when setting all sync options to off.. maybe you can disable that call to the sync API for that case?  would remove need to come up with more insane workarounds.. one of the last remaining issues before i'm comfortable releasing updated images..
😁
🙏

**Comment by Pitmairen** [comment]
I will see if I can remove the call if sync is off.

But it would be nice to know why this happens. When it happens do you see anything useful in `about:sync-log` or the dubug console in `about:debugging#/runtime/this-firefox`?

Maybe this is something similar https://bugzilla.mozilla.org/show_bug.cgi?id=1411691.

**Comment by Pitmairen** [comment]
I have released a new version that doesn't try to load the settings from sync if it is disabled. It should already be available for firefox. 

Hopefully this fixes your issue.

**Comment by eMPee584** [comment]
> dubug console in `about:debugging#/runtime/this-firefox`?

selection search's console shows some errors but it don't seem to be related to the sync error:
![image](https://user-images.githubusercontent.com/1227833/166160105-54966ef9-bbd5-4f1e-b6ee-bca6487df23a.png)
[…]
Ok it seems to be a corrupted / empty 32K `storage-sync-v2.sqlite` file (not an empty one) in the firefox profile that causes this. How it occurs.. 🤔 Maybe because we're using [profile-sync-daemon](https://github.com/graysky2/profile-sync-daemon).. couldn't quite track it down (using `git` to track the whole profile folder btw, very nice technique to figure things out..).
Thanks for adapting those sync calls, I'll keep an 👁 on this 😅
