### ISSUE TITLE
[Question] Help with {%s|replace:

### ISSUE THREAD

**Issue by fosam** [Pitmairen/selection-search#130]
Hei

I'm trying to customize some searches but my lack of RegEx knowledge makes advanced usage so difficult.

I want to replace these gps coordinates format from this one:

https\://website.website.org/website.php?params=**71°00'24.7"N 8°02'31.1"W**

To this one:

https\://website.website.org/website.php?params=**71_0_24_N_8_2_31_W**

How can i proceed with this example?

This is what i was trying but then i coudn't finish it `{%s||replace:/°|'/_/gi}`

**Comment by fosam** [comment]
This definitely works, i would have not figured this out by myself, i really want to learn to get the most out of this good extension like things similar to this kind of searches, do you have any tips on what to learn in order to make this kind of replaces and things like that by myself in the future? i'm really interested.

Thanks!

**Comment by Pitmairen** [comment]
I think it's probably a good idea to try to learn some general programming, Python is probably a good starting language. This will teach you how to think when solving problems using programming, and then you can use the same thinking when solving problems using regular expressions. 

Maybe https://www.codingame.com/ can be a good place to learn and have fun at the same time.

**Comment by fosam** [comment]
Noted, Thanks!
