### ISSUE TITLE
Blacklist only works on mouse, not on hotkeys.

### ISSUE THREAD

**Issue by Alphabet1226** [Pitmairen/selection-search#131]

**Comment by Pitmairen** [comment]
The main reason for the blacklist was to be able to remove it from some sites where the popup did not work or caused issue. 

But it is certainly possible to also disable the hotkeys using the same blacklist. I may add an option to enable it.

**Comment by Alphabet1226** [comment]
Thank you so much, this is one of my favorite extensions!
The need for this came up because I often accidentally trigger it when typing in Workflowy.

**Comment by Pitmairen** [comment]
That's a valid use case. I have added an option to enable the blacklist for the hotkeys, it is enabled by default.

A new version has been submitted and should be available soon (version 0.8.61).

**Comment by Alphabet1226** [comment]
Thank you so much for creating such a great and useful product, and thanks even more for being so passionate about solving the problem, it's great!
