### ISSUE TITLE
Issue with %PAGE_ORIGIN or wrong usage?

### ISSUE THREAD

**Issue by CFR0901** [Pitmairen/selection-search#133]
I have the following tab open:
`http://localhost:8080/abc`

Now, I would like to have something like
`http://localhost:8080/def`

%PAGE_HOST does not contain the port. Hence, this is not possible
`http://%PAGE_HOST/def`

%PAGE_ORIGIN is leading to a real strange behavior
This
`%PAGE_ORIGIN/def`
leads to
`chrome-extension://gacjdandclpjhlbjidmondconlbgjnhd/http%3A%2F%2Flocalhost%3A8080/def`

Did I do something wrong or is this a bug?

**Comment by CFR0901** [comment]
Thank you for the fast response. I will try it out.

P.S.: I'm using chrome on windows and linux.

**Comment by CFR0901** [comment]
Under windows + Chrome with a url without port, it does not work.

**Comment by Pitmairen** [comment]
The extension-id in your example (`chrome-extension://gacjdandclpjhlbjidmondconlbgjnhd`), is different from what I would expect for selection search extension in Chrome, so I'm not sure what's going on there. Do you know what extension the id `gacjdandclpjhlbjidmondconlbgjnhd` belongs to? You should be able to find it under chrome://extensions/


But what are you trying to achieve here? is it something general for multiple sites? or something for a single specific site?

**Comment by CFR0901** [comment]
Okay, maybe it's a little bit miss-use of your extension, but it comes very handy.

In my work, I have to do with cloud products. Hence, the URLs of test landscapes as well as customer landscapes vary quite a lot. Now, I don't like to manage a link collection for the common UIs for every base_url. Hence, I customized the "search engines" to cover the common URLs given the base_url of the currently active tab.

This works very well as long as there is no port part in it.

Further on, I manipulated your extension with a local version where no "input data" is required as sometime no parameter is needed.

**Comment by CFR0901** [comment]
Wow, thank you for that hint. That really work.

Do you plan to add this to your official product?

**Comment by Pitmairen** [comment]
Yes, I can add new versions of these variables without urlencoding. I will try to include it in the next version.

**Comment by CFR0901** [comment]
Hi Pitmairen,

I have opened PR https://github.com/Pitmairen/selection-search/pull/134 therefore. It works fine on my side, but I'm not sure if I added all necessary changes. Feel free to complete the PR or suggest changes ;)

**Comment by Pitmairen** [comment]
Thank you, it looks good, I have merged it. I will see if I get around to releasing a new version tomorrow.

**Comment by Pitmairen** [comment]
I have released the new version. It will take a while for it to be approved and become available. I guess you still need a local version because of the "input data" required modification?

**Comment by CFR0901** [comment]
Yes, that is required anyway. Maybe I will try to add another option therefore in the future ;)
I will close the issue as it is released. Thanks for your help!
