### ISSUE TITLE
missing seaches in Popup Menu

### ISSUE THREAD

**Issue by halcion** [Pitmairen/selection-search#14]
i posted in the google webstore about this already back in July. some search engines in folders display fine in the context menu while others do no show up in the popup menu, pleas fix this. was hoping this would have been fixed by now, but since it hasn't been and there has been no updates to the extension i figured i should report it. i have since reinstalled firefox and started playing with that again, nevertheless, would be nice to see this updated.

**Comment by Pitmairen** [comment]
You need to export your settings from the bottom of the options page and upload them so I can try you config. I haven't experienced this problem so I need your settings for testing.

**Comment by Droyk** [comment]
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Aug 14, 2015, 12:18 PM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/14#issuecomment-130996178 "2015-08-14T06:48:48Z - Replied by Github Comment Enhancer"):
> You need to export your settings from the bottom of the options page and upload them so I can try you config. I haven't experienced this problem so I need your settings for testing.

Nor have i and i think he didn't choose the popup menu for the search engine to load .i am testing this extension my with my three laptops and one computer so i think there is no problem here .so plz close this issue down [Pitmairen](https://github.com/Pitmairen)
