### ISSUE TITLE
Toolbar Popup only searches first search engine

### ISSUE THREAD

**Issue by aramrw** [Pitmairen/selection-search#148]
https://github.com/Pitmairen/selection-search/assets/106574385/23f000b5-46ed-43ec-9980-d8dc358130d3

**All my url options are the same:**
![chrome_iHbGOXkdq6](https://github.com/Pitmairen/selection-search/assets/106574385/cedff53a-6284-4477-a5e7-af4e166ef747)

**My settings:**
![chrome_9OOepHvSuJ](https://github.com/Pitmairen/selection-search/assets/106574385/f5aa140f-c480-4e98-b0d5-20581f7a9166)

I'm just wondering if I'm doing anything wrong or if i forgot to check a setting, or its actually broken or not

**Comment by Pitmairen** [comment]
It's a bit hard to see in the video, but it looks like you do the search by hitting the "enter/return" key. 

That's just the way it works today, hitting the enter key will always open the first search engine. 


I guess we could try to detect clicks on search engines while the input empty, and have the click mark the engine as the default search, and then use this when hitting enter. But this has to be developed.

**Comment by aramrw** [comment]
Yea I realized you have type it first then click on the search engine so my problem is solved, I think that could be a good idea though

**Comment by aramrw** [comment]
Yea I realized you have type it first then click on the search engine so my problem is solved, I think that could be a good idea though
