### ISSUE TITLE
[Suggestion] Alternative auto popup button and menu placement

### ISSUE THREAD

**Issue by bijancamp** [Pitmairen/selection-search#15]
Hi! I really like the "auto" popup menu option, and I wanted to have the auto button appear below my cursor, so that I could easily find it and go to it. Here it is in action after my commit https://github.com/bijancamp/selection-search/commit/be806fffb8f69b5614cd94046a9d79d842f9423b :

![ezgif-2509791771](https://cloud.githubusercontent.com/assets/8800015/9705119/9ace9000-547f-11e5-82da-c897d99415a2.gif)

I wasn't sure if there was a particular reason why the button in the main version appears to the upper right of the selected region, so I may be missing some negative consequence of changing this.

I also repositioned the resulting popup menu so that the first engine name is under the cursor. This makes the first engine easier for me to click, while also making it easy to see the engine icons on the left.

Unfortunately, my changes alter the menu position for every popup style, so it's assumed that the user has selected the "No selection" styling option. I'm not a developer, so I don't know how to properly implement this to work for all styles.

Do you think this kind of behavior has a place in the official version? If it does, then I was thinking there could be an option to toggle between these different possible button positions.

**Comment by Pitmairen** [comment]
Hi, there is no particular reason for the placement of the auto popup button. It was just placed in the upper right of the selection for whatever reason. But a position relative to the cursor is probably a more natural placement.

I don't want to change the default behavior, as it has been like this for years now and i don't know how many are using it. People tend to get pissed of if something suddenly changes.

But making an option to make the button popup relative to the cursor should be easy. Basically what you already did and then add a option on the option page.

And then the position of  both the auto popup button and the popup menu can be tweaked with some custom css. This can probably fix the problem of repositioning the popup to get the first engine name under the cursor without changing the current code. Just tweak the position with the following css:
```css
/* The auto popup button:*/
.button{
    margin-left: ±x px;
    margin-top: ±y px;
}
/* The main popup menu:*/
.mainmenu{
    margin-left: ±x px;
    margin-top: ±y px;
}
```
I will add the option to position the auto popup relative to the cursor soon or right now.

**Comment by bijancamp** [comment]
Thank you! That css works perfectly for me. I'm an extreme CSS newbie, so this was likely what you meant, but I had to use the "popup" class instead of the "mainmenu" one:

```css
.popup{
    margin-left: ±x px;
    margin-top: ±y px;
}
```

Thanks once again. ☺

**Comment by Pitmairen** [comment]
.popup will work also, but this will affect both the main menu and sub menus. But if you'r not using sub menus .popup will work fine. 

But .mainmenu should work at least if you are using the latest version of the extension. It should only affect the main popup.

I will add a new option for the auto popup placement and probably release a new version tomorrow. But I just found a bug I need to fix first.  :)

**Comment by bijancamp** [comment]
You're right, .mainmenu does work. Thank you for the info! (I can't wait to learn more about these languages.)

I am looking forward to the new release. 😀

**Comment by Pitmairen** [comment]
I have uploaded a new version now. It adds an option to position the auto popup button and it also fixes the preview of the auto popup button. :)

I think the following css should make it behave the same as in your demo above:
```css
.button{
  margin-left: -24px;
  margin-top: 36px;
}
.mainmenu {
  margin-top: -8px;
  margin-left: -45px;
}
```

**Comment by bijancamp** [comment]
Thanks! The new update, together with your CSS, works perfectly! 😀

The only possible issue is when text near the bottom of the viewport is selected. In this case, the auto button appears under the cursor, which may make it too easy to activate. (It may be best placed above the cursor if near the bottom edge of the viewport.)

![ezgif-1129583155](https://cloud.githubusercontent.com/assets/8800015/9832448/a18060ca-5940-11e5-8aeb-e80f2fb17de2.gif)

I'm not sure what the proper fix for this would be (if there should be any). In fact, this may not actually be a big deal, since there is a nice delay between selecting text and seeing the popup button.

Once again, thanks for the update. :)

**Comment by Pitmairen** [comment]
Currently the case when the button hits the edge of the window is handled by the same code that handles the popup menu so it will just push the button back into the window without considering the position of the cursor. 

I don't think it's a critical issue, but i will try to fix it in the next release.

**Comment by bijancamp** [comment]
Okay, thanks! Yeah, I don't think it's too critical of an issue either, and I'm happy with the current release. :)

**Comment by Pitmairen** [comment]
The problem with the popup button appearing under the cursor is a bit harder to fix than I first though.
The problem is that I only know the position of the cursor at the time when the user releases the mouse after the selection is made. Any movement of the mouse during the delay before the button is shown is not detected. So I could end up moving the button, thinking it is under the cursor when it is not, and then placing it at the position where the cursor is actually located.  

It is possible to constantly track the mouse position, but I don't know if it wort it just for this. It shouldn't be too hard to get used to the situations where this is a problem and simply move the cursor slightly upwards after making the selection.

**Comment by bijancamp** [comment]
Yes, I agree. I think there will always be the possibility of accidentally opening the menu by hovering over the button. One way to sidestep this issue though is to eliminate the auto popup button altogether, and just have the menu with all of the search engines automatically open. That way, there is no accidental opening of anything.

I have hacked the source in [my personal branch](/bijancamp/selection-search/tree/personal) to make this happen, but my changes are very poor as I do not know how to properly code a solution. Also, my branch is a few commits behind your main one (missing the new circular menu). Here is a demo of the change:

![selection search auto show search engine menu](https://cloud.githubusercontent.com/assets/8800015/10597757/a36a891c-76b7-11e5-856e-e4baa258244a.gif)

The popup menu automatically shifts up a few pixels if the selection is near the bottom of the viewport.

**Comment by Pitmairen** [comment]
This can probably be easier implemented now using the [PopupModifier](https://github.com/Pitmairen/selection-search/blob/master/popup/popup_modifier.js) that I added to create the circular menu. The circular menu is implemented as a popup modifier. 

The modifier can for example change the position of the popup by centering it over the mouse cursor without the need to change the code in the activators. And then all that is needed is a a new activator that can auto open the popup or modify the existing auto activator to optionally show the menu directly without the auto button.

**Comment by bijancamp** [comment]
I think that sounds great! I will try to add this option to show the menu directly this weekend, along with a mechanism for moving the menu if the selection is near one of the edges. :D

**Comment by bijancamp** [comment]
Reviewing the new code in the Auto activator section of [options/options.html](https://github.com/bijancamp/selection-search/blob/2dff3e34ba09d49675ec2da11a8d19b0e1728292/options/options.html), there should probably be a comment that positioning the button relative to the mouse only makes sense if the new option to auto-show the menu directly is not selected. Alternatively, this relative-positioning option could be hidden or greyed out if the new option is selected.

**Comment by bijancamp** [comment]
Commit 3cfb043e8cb02bac14e936af670889aa6e2aecc4 resolves this issue of the popup button appearing under the cursor, and of the menu obscuring the selection, whenever the selection is near one of the window's edges. See Pull Request #21 for the details on how these scenarios can now be prevented from occurring.
