### ISSUE TITLE
The plugin works abnormally in different areas of the page

### ISSUE THREAD

**Issue by microdockman** [Pitmairen/selection-search#160]
For example: https://www.bilibili.com/video/BV1z4411Y7tX
In the video title section, just select the keyword and click the mouse once

In the comments section, I need to click twice in a row, which will cause the selected keywords to change, I did not change any Settings, in the previous version everything is fine

chrome ver 126.0.6478.127（ x64 )

**Comment by Pitmairen** [comment]
I can not reproduce the problem.  It's just one click for me.

**Comment by microdockman** [comment]
> I can not reproduce the problem. It's just one click for me.

Just reset the browser. Simply clearing cookies doesn't work. The problem has been solved

**Comment by microdockman** [comment]
> I can not reproduce the problem. It's just one click for me.

Sorry I still have to open the question, very strange, I log in to the account, the above problem occurs,  exit the account to restore normal

**Comment by Pitmairen** [comment]
The page is most likely doing something that interferes with the extensions.

If you try to open the popup and then after it fails, right click somewhere on the page an select "inspect".

![image](https://github.com/Pitmairen/selection-search/assets/357032/ba0ac58a-5c86-4b2e-93c0-ec6e1d845680)

Then look in the console tab to see if there are any error messages:

![image](https://github.com/Pitmairen/selection-search/assets/357032/989e1bdf-2b34-4604-b42c-0bdf8366d08d)



Maybe try both when logged in, and when not logged in, and compare the console output to see if there are any differences.

**Comment by microdockman** [comment]
> The page is most likely doing something that interferes with the extensions.
> 
> If you try to open the popup and then after it fails, right click somewhere on the page an select "inspect".
> 
> ![image](https://private-user-images.githubusercontent.com/357032/346825934-ba0ac58a-5c86-4b2e-93c0-ec6e1d845680.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg5MjEsIm5iZiI6MTcyMDUxODYyMSwicGF0aCI6Ii8zNTcwMzIvMzQ2ODI1OTM0LWJhMGFjNThhLTVjODYtNGIyZS05M2MwLWVjNmUxZDg0NTY4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwOTUwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTJmN2I4ZWEzZmY3NjQ5OTE1NTMxMDc5ZTcyNGE1MDQ3OGFjYjMwY2UwZmFkNmRlYjE3MzNhYTNlNjFiMjdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.usyhLhsTWRwzh3tAtk_i2GzzPoaOZ5Xec9kX8E-6Bws)
> 
> Then look in the console tab to see if there are any error messages:
> 
> ![image](https://private-user-images.githubusercontent.com/357032/346826244-989e1bdf-2b34-4604-b42c-0bdf8366d08d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTg5MjEsIm5iZiI6MTcyMDUxODYyMSwicGF0aCI6Ii8zNTcwMzIvMzQ2ODI2MjQ0LTk4OWUxYmRmLTJiMzQtNDYwNC1iNDJjLTBiZGY4MzY2ZDA4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQwOTUwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjk0MTU2NDMxMzQxZjgxYWRiMTg4NDE4MTI4MGNhZjQ2NjBkY2FmMTgwYmUzNzdkYjY3NmEwZGExNjE2YTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K5DvfqtfRpf6xKWBTIhJzSPbYk0cf-P3eEusttcdLvs)
> 
> Maybe try both when logged in, and when not logged in, and compare the console output to see if there are any differences.

![1](https://github.com/Pitmairen/selection-search/assets/31898637/4aa50859-bb3b-4a61-b9a6-b7f942a66507)
login



![2](https://github.com/Pitmairen/selection-search/assets/31898637/c5d20bf8-4be6-4677-b793-342c86f7682f)
logout（Function is normal）
