### ISSUE TITLE
[BUG] Popup menu box is not appearng

### ISSUE THREAD

**Issue by Droyk** [Pitmairen/selection-search#26]
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.

so when i select a text there was a ![Smallbox](http://i.imgur.com/MKiwTD1.png) that should appear but its not appearing 

when i select a text all the icons appear directly ........first there should be a box that display first but now there is none.i don't know why ?

http://i.imgur.com/ONvDw31.png

and instead of a small box i am directly getting the ![Direct access](http://i.imgur.com/VbvICkq.png)

**Comment by Pitmairen** [comment]
Its because of the check box right above your red square.  "Show the menu directly when selecting text"

You have to uncheck this checkbox.

**Comment by Droyk** [comment]
[**@Pitmairen**](https://github.com/Pitmairen) commented on [Jan 25, 2016, 7:58 PM GMT+5:30](https://github.com/Pitmairen/selection-search/issues/26#issuecomment-174523105 "2016-01-25T14:28:49Z - Replied by Github Comment Enhancer"):
> Its because of the check box right above your red square.  "Show the menu directly when selecting text"
> 
> You have to uncheck this checkbox.

why i didn't see that bix box just why i didn't read it properly sorry [Pitmairen](https://github.com/Pitmairen) to disturb you over something like this 
 I am really a stupid one .thanxx
