### ISSUE TITLE
Enable selection search to work inside local files opened in chrome

### ISSUE THREAD

**Issue by Bortseb** [Pitmairen/selection-search#3]
i.e. "enable access to file URLs"
Sometimes I like to create Local HTML files, and open them in chrome. It would be great if selection search worked within these.

**Comment by Pitmairen** [comment]
This should be easy to add. But the user will have to allow the file access as noted on this page: https://developer.chrome.com/extensions/match_patterns

**Comment by Bortseb** [comment]
Yep! When I tried to use selection search on a local file, and it didn't
work.... the first thing I looked for was the checkbox to enable file URL
access for the extension.

**Comment by Pitmairen** [comment]
Will release a new version later today which adds support for file:// urls. You will need to check the checkbox for "Allow access to file URLs" in the extension list (chrome://extensions/) to make it work.

**Comment by Bortseb** [comment]
Thanks for being awesome!

**Comment by Droyk** [comment]
[Pitmairen](https://github.com/Pitmairen) plz close this issue it is seem to be fixed
