### ISSUE TITLE
Searches that uses the POST method aren't working 

### ISSUE THREAD

**Issue by Droyk** [Pitmairen/selection-search#32]
Hey developer as the title says searches that uses the POST method aren't working don't know why 
for more information see this screenshot
![image](https://cloud.githubusercontent.com/assets/15848350/22562354/2adfbaf8-e9a2-11e6-97b5-15800bfda341.png)
plz fix it.

**Comment by Pitmairen** [comment]
I will have  a look at it. What version of Chrome are you using?

**Comment by Pitmairen** [comment]
Ok, I have confirmed the problem. I will fix it later today.

**Comment by Droyk** [comment]
Sorry for the late reply I am using the latest version of chrome Version 56.0.2924.87 (64-bit)

**Comment by Pitmairen** [comment]
It should be fixed in version 0.8.16

**Comment by Droyk** [comment]
confirmed now it runs okay.
