### ISSUE TITLE
Option to execute ALL my searches at once

### ISSUE THREAD

**Issue by Bortseb** [Pitmairen/selection-search#4]
If there was an option to execute all my searches at once (including copy to clipboard)....
i.e. an option at the bottom of my pop-up menu...
I would enable it.

**Comment by Pitmairen** [comment]
There is currently an option to open all searches placed in a sub menu. But its currently not possible for the top level menu. But it shouldn't be too hard to add.

**Comment by Bortseb** [comment]
Sweet! I just set up what I was looking for using sub menus... It actually already has the option to no open the sub menu on hover... so this is actually exactly what I wanted...

1 Problem though... The COPY search URL doesn't seem to be working when executed from a sub-menu in this way... (The COPY option when used on the top level is working fie still though)

**Comment by Pitmairen** [comment]
Yes i know, i will fix it.

**Comment by Bortseb** [comment]
OH! your first comment was referring to the COPY option? sorry

**Comment by Pitmairen** [comment]
The copy option should be working in the latest code. I will release a new version later today.

**Comment by Droyk** [comment]
this issue is fixed too [Pitmairen](https://github.com/Pitmairen) plz close this
