### ISSUE TITLE
Save button location

### ISSUE THREAD

**Issue by Elementari** [Pitmairen/selection-search#44]
Since the extension does not auto-save settings, it would be good if the save buttons were positioned at the top of the settings page, and possibly highlighted.

**Comment by Pitmairen** [comment]
Hi, I am thinking about redesigning and creating a new options page. I have started doing some prototyping for the new page, but i'm not sure when it will be done. 

But I agree, the current save button position is not optimal. I will modify the current options page and place the save button in a fixed position that is always visible inside the view.

**Comment by Pitmairen** [comment]
In version 0.8.28, the save button should show up at the bottom of the view when changes are detected, so you don't have to scroll to the bottom.
