### ISSUE TITLE
[Bug] Open all on click without menu doesn't work at all

### ISSUE THREAD

**Issue by shruru** [Pitmairen/selection-search#45]
Thanks for this great ext. I use it everyday . 

However I just found it doesn't work at all, If a submenu's option is checked:
"Open all on Click" **WITH** the option enabled :" Don't show menu" . 

It does work if the "Don't show menu" is disabled. But I wanna it enable so that I don't have to move to the submenu to click the button :"Open All" which is needless everytime.

I tried all the setting combination , didn't work.
Hope I said it clearly. Thanks in advance. Attached 2 pics of my settings of Submenu and the Search item. 

P.S My Chrome is up-to-date version under MacOS 10.13.4

![xnip2018-05-04_13-38-30](https://user-images.githubusercontent.com/2038477/39614198-974a5198-4fa0-11e8-8e63-52a4e90c99bd.jpg)
![xnip2018-05-04_13-38-56](https://user-images.githubusercontent.com/2038477/39614233-e0fb904a-4fa0-11e8-92fa-c37c5055ac63.jpg)

**Comment by Pitmairen** [comment]
Yes, I can confirm that this is a bug. It should be easy to fix. I will try to upload a fix later this evening.

**Comment by Pitmairen** [comment]
I uploading a new version, and it should be fix when you get version 0.8.34.
