### ISSUE TITLE
Copy to Clipboard

### ISSUE THREAD

**Issue by ribatamu** [Pitmairen/selection-search#48]
Could you add "Copy to Clipboard" in the panel?

**Comment by Pitmairen** [comment]
You can use the special value "COPY" as a search url, when clicking the search engine  the selection should be copied to the clipboard. 

Although I just noticed a small bug when using it in the popup in the toolbar, the copying works, but when clicking the engine you will be left with  a "not found" error page. But if you don't use the popup in the toolbar, this will not affect you.
