### ISSUE TITLE
【Can all submenus be displayed in the main interface ?】

### ISSUE THREAD

**Issue by 990721830** [Pitmairen/selection-search#49]
嘤嘤嘤 
The key combination add an engine is too nice....
Can you add a submenu to the main interface options display? 
I want to show all... 
Not a mouse move... pop up a new interface... 
Or can like my video demo ...Separator instead of submenu...

https://drive.google.com/file/d/1g26R7qv-1TQ0MNom7pASjL84hncenMVl/view

English  is not good...Can you understand?

**Comment by Pitmairen** [comment]
So you want  the sub menus to be included inline in the main popup, so you get some sort of grouping of searches in the main menu? Could separators be used for this? ("Add New Separator" button)

**Comment by 990721830** [comment]
yes...
 And can you add a browser touch to pop up the main popup?
like [bookmark-sidebar ](https://chrome.google.com/webstore/detail/bookmark-sidebar/jdbnofccmhefkmjbkkdkfiicjkgofkdh)
![2018 12 15 06 29 26](https://user-images.githubusercontent.com/25548230/50033432-79e69f00-0033-11e9-8744-255be10e6030.gif)
