### ISSUE TITLE
"Preview" section under the "Advanced Settings" of "Styling" doesn't work.

### ISSUE THREAD

**Issue by ghost** [Pitmairen/selection-search#5]
![untitled](https://cloud.githubusercontent.com/assets/8393129/7209083/792112ce-e545-11e4-9bfa-19adb369f1f3.png)

**Comment by Pitmairen** [comment]
Thanks, it is fixed in version 0.7.26.

**Comment by Droyk** [comment]
Just tried it fixed too [Pitmairen](https://github.com/Pitmairen) plz close this issue now
