### ISSUE TITLE
Not shown on click when configured for both mouse click AND double-click

### ISSUE THREAD

**Issue by tophf** [Pitmairen/selection-search#51]
Setup: activated on mouse click AND on double-click.
<details><summary>Exported config "other settings"</summary>eyJzZWFyY2hFbmdpbmVzIjpbeyJuYW1lIjoiR29vZ2xlIiwidXJsIjoiaHR0cDovL2dvb2dsZS5jb20vc2VhcmNoP3E9JXMifSx7Im5hbWUiOiJZb3V0dWJlIiwidXJsIjoiaHR0cDovL3d3dy55b3V0dWJlLmNvbS9yZXN1bHRzP3NlYXJjaF9xdWVyeT0lcyJ9LHsibmFtZSI6IlN0YWNrb3ZlcmZsb3ciLCJ1cmwiOiJodHRwOi8vc3RhY2tvdmVyZmxvdy5jb20vc2VhcmNoP3E9JXMifV0sInN0eWxlU2hlZXQiOiIiLCJvcHRpb25zIjp7ImJ1dHRvbiI6MCwibmV3dGFiIjpmYWxzZSwiYWN0aXZhdG9yIjoiY2xpY2siLCJyZW1vdmVfaWNvbnMiOiJubyIsInNob3dfaW5faW5wdXRzIjpmYWxzZSwiYmFja2dyb3VuZF90YWIiOmZhbHNlLCJrX2FuZF9tX2NvbWJvIjpbMTcsMCwwLDAsMCwwLDAsMCwwLDAsMCwwLDAsMF0sImNvbnRleHRfbWVudSI6ImRpc2FibGVkIiwidG9vbGJhcl9wb3B1cCI6ImVuYWJsZWQiLCJ0b29sYmFyX3BvcHVwX3N0eWxlIjoiZGVmYXVsdCIsInRvb2xiYXJfcG9wdXBfaG90a2V5cyI6ZmFsc2UsInRvb2xiYXJfcG9wdXBfc3VnZ2VzdGlvbnMiOnRydWUsInNlcGFyYXRlX21lbnVzIjpmYWxzZSwiaGlkZV9vbl9jbGljayI6dHJ1ZSwiZGlzYWJsZV9mb3JtZXh0cmFjdG9yIjp0cnVlLCJvcGVuX29uX2RibGNsaWNrIjp0cnVlLCJvcGVuX25ld190YWJfbGFzdCI6ZmFsc2UsImRpc2FibGVfZWZmZWN0cyI6dHJ1ZSwiYXV0b19wb3B1cF9yZWxhdGl2ZV90b19tb3VzZSI6ZmFsc2UsImF1dG9fcG9wdXBfc2hvd19tZW51X2RpcmVjdGx5IjpmYWxzZSwiYXV0b19wb3B1cF9pbl9pbnB1dHMiOmZhbHNlLCJhY3RpdmF0b3JfY29tYm8iOltdLCJzaG93X3Rvb2x0aXBzIjpmYWxzZSwiY2lyY3VsYXJfbWVudSI6ZmFsc2UsInNvcnRfYnlfY2xpY2siOmZhbHNlLCJzZWxlY3Rpb25fbGVuZ3RoX2xpbWl0IjotMSwiYXV0b19oaWRlX2RlbGF5IjoyMDAwLCJhdXRvX29wZW5fZGVsYXkiOjMwMH0sIlZFUlNJT04iOiIwLjguNDEifQ==</details>

---

Repro: 
1. open https://example.org
2. select some text by single-clicking, moving the mouse, release the button
3. click the selection.

Expected: the popup is shown
Observed: nothing happens

---

Debugging reveals the popup is shown here:
https://github.com/Pitmairen/selection-search/blob/b7d442c3444f00ca4557cc69132c7927f12634b4/popup/activators.js#L119

and immediately hidden here:
https://github.com/Pitmairen/selection-search/blob/b7d442c3444f00ca4557cc69132c7927f12634b4/popup/activators.js#L155

An older version of Selection Search 0.7.23 works correctly in this scenario.

**Comment by Pitmairen** [comment]
Yes, i can confirm the issue. I will try to create a fix for it.

**Comment by Pitmairen** [comment]
I removed the hide call that you was referring to and the single click activation should now work again, even when double click activation is active. It should be available in version 0.8.42. 

Thanks for the bug report :)
