### ISSUE TITLE
I can't activate popup or toolbar popup with break line text

### ISSUE THREAD

**Issue by alivefromupstairs** [Pitmairen/selection-search#54]
![image](https://user-images.githubusercontent.com/46059092/52231664-71cc1280-28b2-11e9-87a4-ccdf43ce8b0a.png)
While context menu works just fine, popup doesn't work and toolbar popup doesn't have the selected text.
Great work.

**Comment by Pitmairen** [comment]
Yes, it is intentional. It was done because, when there was line breaks in the selection, the popup would sometimes be activated when it was not supposed to. The context menu is not affected by this, because it works differently.

It can be seen at the following line in the code:
https://github.com/Pitmairen/selection-search/blob/master/popup/selection_util.js#L22

It can be fixed with an option though. It should be easy to add, and then it will work if the option is enabled. I will fix this soon.

**Comment by Pitmairen** [comment]
There should be a new option now in version 0.8.45, under the "Other option", to allow newlines in the selection.

**Comment by alivefromupstairs** [comment]
can you replace the line break with space: the way to works in chrome (and Selection Search context menu )?
![image](https://user-images.githubusercontent.com/46059092/52641933-e239eb80-2ed1-11e9-9438-67c840169fd3.png)
while the popup and the toolbar would collide them
![image](https://user-images.githubusercontent.com/46059092/52642045-21683c80-2ed2-11e9-8b0c-14169998d6fe.png)
![image](https://user-images.githubusercontent.com/46059092/52642077-30e78580-2ed2-11e9-8c8f-6f0738920a5e.png)

**Comment by Pitmairen** [comment]
Yes, I guess that is probably useful for most searches.

But sometimes it can be useful to keep the newlines also.  So I think I will replace the newlines by default, but have a new special placeholder that can be used if the newlines should be preserved for some search engines.

**Comment by Pitmairen** [comment]
I wil release a new version now where the newlines are replaced with spaces. I may later add an option to make it possible to keep the newlines if for some searches.

**Comment by alivefromupstairs** [comment]
@Pitmairen, I'm curious to what scenarios that may be useful? fill out forms or what exactly?

**Comment by Pitmairen** [comment]
One example is google translate. When newlines are replaced with spaces you will lose the formatting of the text if it contains paragraphs etc. Everything will be on a single line. 

So it could be useful to keep the newlines in some cases. But this feature is not something I prioritize at the moment.

**Comment by alivefromupstairs** [comment]
oh yeah. as you said, the option should be search engine specific. 👍
