### ISSUE TITLE
【 Can you add the sidebar engine jump function?】

### ISSUE THREAD

**Issue by Noah1995** [Pitmairen/selection-search#56]
![【2019 03 13】【00∶54∶42】](https://user-images.githubusercontent.com/25548230/54219597-cb1b0780-452a-11e9-9197-83a908617ef6.gif)

Can you add the sidebar engine jump function?
Just like the method of the【SearchBar 】 ...
Left or right ...
https://chrome.google.com/webstore/detail/searchbar/fjefgkhmchopegjeicnblodnidbammed?hl=zh-CN&gl=US

**Comment by 990721830** [comment]
![【2019 03 14】【18∶11∶13】](https://user-images.githubusercontent.com/25548230/54350859-30850a80-4689-11e9-9e31-f4672a6847be.gif)

**Comment by Pitmairen** [comment]
So you want a bar like the one on the top in the screenshots, but on the side instead?

**Comment by Pitmairen** [comment]
Just a quick test by just using custom styling. This will show the popup as a bar on the left side of the window:

```
.popup.mainmenu{
 padding-top: 1em;
 width: 200px;
 top: 0 !important;
 left: 0 !important;
 height: 100%;
 position: fixed;
 border:none;
 box-shadow: none;
 border-right: 1px solid #ccc;
}
.popup.mainmenu .engine-name{
 width: auto;
}
.popup.mainmenu .engine-url{
 padding: 0.6em 0.4em;
}
.popup.mainmenu > li:first-child{
 background: #fafafa;
 padding: 0.5em;
}
```

Add the above to options -> popup menu -> advanced settings -> customize -> textarea. (Only the above css should be in the textarea).

**Comment by 990721830** [comment]
Is work...

But can you add a pin and cancel button to the Popup Menu?

Enable all web pages to open or close the Popup Menu...

And  the input field remembers the text just used the jump ...

And add 【SearchBar displaces web pages】

![【2019 03 15】【15∶58∶49】](https://user-images.githubusercontent.com/25548230/54416828-76021000-473b-11e9-83ea-e78c898602f1.gif)

**Comment by Pitmairen** [comment]
Maybe, I will look into it and see if, at lease some of it, can be added without too much work. But i'm currently working on a new options page, and I'm prioritizing that at the moment.
