### ISSUE TITLE
where is "copy" and "open url in new tab"

### ISSUE THREAD

**Issue by kktt007** [Pitmairen/selection-search#59]
As the title. I just could find the copy and open url in new tab. Normally "open url in new tab" is quitely useful. Thank you , my author.

**Comment by Pitmairen** [comment]
If you want to copy, you can add a new search engine and use the special value "COPY" (without quotes) as the search url. This will copy the selection to the clipboard.

To open the search in a new tab, there should be an option under the "Other options" section, where you can select "Open search in new tab". There is also an option for each search engine, if you click on the wrench next to the search engine.

**Comment by lan542662** [comment]
Thank you so much, i solve the question 1. Thank you for telling search in
a new tab, now i could search in background tab. Thank you so much.
Actually, i want to konw if  there an option, when i select a website:
like: google.com, then we could open the selected website in a new tab.
At last, do you got a plan to add this extension to firefox.
Thanks for you excellent work.
Best regards.

Per <notifications@github.com> 于2019年4月22日周一 下午2:29写道：

**Comment by Pitmairen** [comment]
To open the selected website url in a new tab, you can try to add a new search engine and use just: "%s" (without quotes) as the search engine url, this should open the selected url.

The extension is already available for firefox: https://addons.mozilla.org/en-US/firefox/addon/selection-search-ff/

**Comment by lan542662** [comment]
Thank you, I have solved all my questions.now I think you could add them to
the default (just my suggestions, maybe my english is pool, so i didn't
find it), it;s so cool and useful.
I used swift selection search on firefox before. But now i will choose this
extension.Because i didn't know firefox got have this extension. so i will
use selection search instead. Thank you so much.
Happy everyday to you.~~

Per <notifications@github.com> 于2019年4月22日周一 下午6:27写道：

**Comment by Pitmairen** [comment]
I'm working on a new options page that will make it easier to use and also make these special features more visible.

**Comment by lan542662** [comment]
May i know which new options? ~~😁

Per <notifications@github.com> 于2019年4月23日周二 下午1:26写道：
