### ISSUE TITLE
Column/Matrix layout?

### ISSUE THREAD

**Issue by eMPee584** [Pitmairen/selection-search#6]
Would be really nice if the popup would break into multiple columns on https pages.. but more a matrix layout for icon-only mode would probably look nice, too..

**Comment by Pitmairen** [comment]
The style used for https pages is the default style, but with the icons removed. The reason for this is that if some of the icon urls don't use https you will get a warning about insecure content. If you don't care about this you can set the "Always show icons" options in the advanced settings of the popup.

The icon only style can be made into an matrix by appending this css to the style:
```
#popup {
 width: 90px;
}
```
Modify the witdh to get the number of columns you want.

**Comment by Droyk** [comment]
Fixed i think so close it down [Pitmairen](https://github.com/Pitmairen)

**Comment by eMPee584** [comment]
Yes fixed, thx!

**Comment by eMPee584** [comment]
Ok this is kind of what I had in mind:

```
.mainmenu > li:first-child{
 display: none;
}

/* workaround against hard-coded popup style "display:block" */
.popup:not([style*="display: none"])
{
    display: grid !important;
}

.popup {
    width: unset; /* reset width from fixed 12em to auto */
    grid-auto-flow: column;
    grid-template-rows: repeat(25, auto);
    transform: scale(1.25);
    border-radius: 1em;
}

/* Put a spacer element at the end of the grid */
.popup:after {
    content: " ";
    flex: 999 999 auto;
}

/* allow engine names to be wider */
.popup .engine-name {
    width: unset;
    max-width: 12em;
}

/* WE THE short-sighted PEOPLE like bigger buttons */
.button {
 width: 48px;
 height: 48px;
 background-image: url("moz-extension://32aa219d-fc0b-44b4-af76-d9266ec10e2c/img/icon48.png") !important;
}
```

![image](https://user-images.githubusercontent.com/1227833/89109060-1c88a700-d43e-11ea-801d-f6f38024481b.png)

just can't get the separators to center .. And I wanted to confine the number of rows relative to screen size (max-height: 60% or something) but couldn't get that to show

**Comment by Pitmairen** [comment]
maybe you can use `max-height: 60vh;` if % doesn't work.

**Comment by eMPee584** [comment]
yeah well it does set a max height for the popup but it doesn't reflow the grid accordingly, it still needs the `grid-template-rows: repeat(25, auto);`..
