### ISSUE TITLE
Can't save (Firefox 67 x64)

### ISSUE THREAD

**Issue by zmni** [Pitmairen/selection-search#61]
Clicking save button doesn't do anything, closing and reopening addon option page revert everything back to it's original/default state.

**Comment by Pitmairen** [comment]
I can confirm that it does not work. There is a timing issue between the local store and the sync store, causing the sync store to overwrite the changes with the old value.

A temporary fix is to disable all options under the "Synchronization" section on the options page (if you are able to save these settings).

I will create a fix later today.

**Comment by Pitmairen** [comment]
Should be fixed in version 0.8.48.1 for firefox.

**Comment by zmni** [comment]
Thank you.
