### ISSUE TITLE
Selection search popup should dismiss on scroll event

### ISSUE THREAD

**Issue by bsiegel** [Pitmairen/selection-search#65]
Many times I select text with the mouse as I am reading through an article, and I want to dismiss the popup but not deselect the text. There is no way to do this currently. Swift Selection Search for Firefox dismisses the popup on scroll which feels like a reasonable solution. This could be added as a preference, but I wouldn’t say it’s required.

**Comment by Pitmairen** [comment]
Under "advanced settings" there is an option "Auto hide Delay" that, if enabled, closes the popup after a certain delay (as long as the mouse is not over the popup).

I think that mostly solves this issue? 

But it shouldn't be too hard to add an option to dismiss the popup on scroll also.

**Comment by bsiegel** [comment]
Another good event to dismiss the popup is when the window/tab loses focus.

**Comment by Pitmairen** [comment]
Option to hide on scroll will be included in next release.
