### ISSUE TITLE
“Copy” action should copy raw text including linebreaks

### ISSUE THREAD

**Issue by bsiegel** [Pitmairen/selection-search#66]
I see that linebreaks have to be escaped in order to do a search, but when copying to the clipboard it’s important to maintain the linebreaks exactly as they were.

**Comment by Pitmairen** [comment]
Yes, that is a good point. Previously it was not possible to open the popup when the selection contained newlines, so it was not  a problem. But now there is an option to allow newlines, so the copy option should probably always use the raw selection.
