### ISSUE TITLE
Using Multiple activator and "Animation 2" styling bug.

### ISSUE THREAD

**Issue by ghost** [Pitmairen/selection-search#7]
Using Multiple activators i.e. "Mouse click + Auto"..
and "Animation 2" styling..
Makes left clicking a selected text which is a "link" be opened, instead of showing the popup menu.

**Comment by Pitmairen** [comment]
Should be fixed in the latest code.

**Comment by Droyk** [comment]
This issue seem to be fixed so plz close this issue right now
