### ISSUE TITLE
My selection search options change on their own

### ISSUE THREAD

**Issue by Bortseb** [Pitmairen/selection-search#72]
I'm frequently having to change my options to how I like them. What keeps changing is my option for what triggers the popup menu. I keep changing it to middle click, then saving the options... and for some reason it keeps changing back to left-click and I need to go back in to change it again.

**Comment by Pitmairen** [comment]
I haven't seen this before. Are you using multiple computers with syncing enabled?

**Comment by Bortseb** [comment]
Yes, I use selection search on my desktop and laptop through the same google account... But both are using middle click to activate the popup.

**Comment by Pitmairen** [comment]
Does it happen on both computers? how long does it take before the option changes?

Is this something that has started recently, or has it been like this for a long time?

**Comment by Bortseb** [comment]
it happens on both as far as I can recall, though I use my laptop much less... and its been like this for a while now... though its hard for me to pinpoint when first noticed it happening..

**Comment by Pitmairen** [comment]
I will try to change my settings to use the middle button and see if I can reproduce it. 

Both your computers are using the same/latest version of the extension I presume?

**Comment by Bortseb** [comment]
yea, it all auto-updates as far as I know

**Comment by Pitmairen** [comment]
I'm able to reproduce the problem now, so hopefully I can find a fix.

**Comment by Pitmairen** [comment]
Should be fixed in version 0.8.51.
