### ISSUE TITLE
Setting resets to default after quitting browser

### ISSUE THREAD

**Issue by bsiegel** [Pitmairen/selection-search#73]
I am trying to use the newly added setting "Open on double click > Enabled in inputs/textareas". I can toggle it off and save, and it works. However if I quit the browser entirely and reopen it, the preference is reverted to the default (enabled).

**Comment by bsiegel** [comment]
I have not noticed the same behavior for other settings.

**Comment by Pitmairen** [comment]
I will review the save settings code. I saw something similar in the firefox version of the extension a while ago, but in firefox the settings was not saved at all. I think could be some timing issue in the way the settings are stored in the sync-store and local-store. 


#72 is probably the same issue.

**Comment by Pitmairen** [comment]
It looks like it was the same issue as in firefox. Should be fixed in version 0.8.51.
