### ISSUE TITLE
JQuery Update

### ISSUE THREAD

**Issue by keatond** [Pitmairen/selection-search#78]
Hello!

Seeing if it is feasible to update to the newest JQuery. The current one is vulnerable to Prototype Pollution attacks.

**Comment by Pitmairen** [comment]
Yes, I will try create a new release with an updated jquery very soon.

**Comment by keatond** [comment]
That is amazing news! Thank you so much for being so responsive!

**Comment by Pitmairen** [comment]
I have released  a new version. It is currently pending review by google in the web store. It can take 1-2 working days according to google.

**Comment by Pitmairen** [comment]
Still pending review. Hopefully it does not end up like my other extension which have been stuck in pending review state for months.

**Comment by keatond** [comment]
Ok no worries, Thanks for such a quick turn around.

**Comment by keatond** [comment]
Looks like the Extension updated! Thanks again! I'll close the issue.
