### ISSUE TITLE
Popup Menu is always under Youtube's top bar.

### ISSUE THREAD

**Issue by ghost** [Pitmairen/selection-search#8]
"Ctrl+ left clicking" a selected text in Youtube's input textarea appears infuriatingly under the top bar.

**Comment by Pitmairen** [comment]
This is because of the z-index on the top bar. 

A temporary fix until i get to update the extension is to customize your current style and add the following:

```
#popup{
    z-index: 2147483647 !important;
}
```
This will only work if you have not checked the "Use default style on https pages" option.

**Comment by Pitmairen** [comment]
This is fixed in the latest version of the code. A lot of the code has changed so it needs some more testing before uploading to the  web store.

**Comment by Droyk** [comment]
just checked it .it is fixed so plz close this issue down [Pitmairen](https://github.com/Pitmairen)
