### ISSUE TITLE
Fix for freezing tabs for searches opened in new foreground tab

### ISSUE THREAD

**Issue by uvrem** [Pitmairen/selection-search#83]
@Pitmairen,

I recently made a report to you for freezing tabs for searches opened in new foreground tab.

I am opening this issue, because the original one dissapered from github and I would like to let you know how the version 0.8.55 is fixing the behavior.

The video with the bug can be found at https://streamable.com/wm3yq

Please feel free to close this issue.

**Comment by Pitmairen** [comment]
Yes, I remember the issue, it disappeared. 

The video is from before the fix, right? With 0.8.55 is no longer freezes?

**Comment by uvrem** [comment]
The video is before the version 0.8.55.

Thank you for finding and fixing the behavior.

**Comment by Pitmairen** [comment]
I forgot to answer last week. Great to hear that the fix worked. 

I'm just closing the issue now that it works.
