### ISSUE TITLE
Suggestion about the Disable effects

### ISSUE THREAD

**Issue by lyscop** [Pitmairen/selection-search#87]
I want to suggest that when I test the fade in/out function, it works not well, it just seems like setTimeout(function(){icon.style.display='block'}, 600); instead of fadein(); or fadeout(); , and it is fake. I am glad that you can take the time to check it.

Selection Search is the most perfect extension of selection search in Chrome, even though there are many good context search apps in Firefox. Thank you for creating this for us, and thank you update frequently.

Since I found that I could add a search engine to copy the selected word to the clipboard and open the selected link as a URL in the new tab in background, I feel it is wonderful.

**Comment by Pitmairen** [comment]
Yes, you are right, the code does not seems not use any effects any more, it simply sets `style.display='block'`, like you mentioned. I don't remember when this was changed, I haven't really noticed it.

It should be easy to add effects back, I will do some testing and see how it looks.

**Comment by lyscop** [comment]
Dear Pitmairen,

Thank you for taking notice of this suggestion.

I beg you that can you help me a little more.

It is a fact that Chrome does not support to visit the windows clipboard. I find that Chrome has an API that supports store the message today, and it only can be used in an extension, can not be used by JavaScript.

[https://developer.chrome.com/apps/storage](https://developer.chrome.com/apps/storage)

```javascript
	chrome.storage.local.set({key: value}, function() {
          console.log('Value is set to ' + value);
        });
      
        chrome.storage.local.get(['key'], function(result) {
          console.log('Value currently is ' + result.key);
        });
```


I test all the paste extensions in the Chrome Store, and there is no one support popup just context menu when selecting the text, then it will be stored to the chrome storage container, it also can be pasted in the input box of a website.

Selection Search is the most perfect popup search extension in Chrome. Here I beg you that can you help me to add the two functions?

First, the other Copy function, when selecting the text, click the icon, and the selected text will be stored to the chrome storage container and be copied to Windows clipboard at the sometimes.

Second, the Paste function, when the mouse focus on the input box, then paste icon will popup, it will paste the last stored text into the input box if I click the paste icon.

Why I need this because it will be efficient instead of shortcut, and there is no program in Windows instead of [Popcilp for Mac](https://pilotmoon.com/popclip/) which likes long-tapping the screen on the phone, and then copy/paste/delete will popup above the selected text. 

Thank you so so so much if you take them into consideration again.

Best.

**Comment by Pitmairen** [comment]
The chrome.storage api will not store the content in the clipboard. It is just storage that the extension can use to save settings and other data. 

It is possible to read/write to the clipboard if the extension has the clipboardRead/clipboardWrite permissions (https://developer.chrome.com/extensions/declare_permissions).

Selection search has the clipboardWrite permission, and there is already a feature to copy the selected text to the clipboard that works by adding a special search engine with the url set to COPY. When clicking this search engine the selection should be copied to the cliboard. (I have never test it on windows, but it works on linux and osx).

Selection search does not have the clipboardRead permission that is needed to implement paste. I'm not sure I want to request any more permissions as google is quite strict when approving extensions that requires a lot of permissions. I already have some issues getting the extension approves, as google have to review the extension every time I make a change because of the current required permissions, and it can take quite some time.

**Comment by lyscop** [comment]
I am glad to hear from you.

Yeah, you are absolutely right, the API of Chrome is so so bad, and thank you notice me again.

Maybe I did not make it clear. The COPY function now in the Selection search is useful.

Simply, I want to copy to chrome storage, paste from chrome storage, and copy to window clipboard.

The first function is another copy function, it is that use the chrome storage API to store the selected text.
And use document.execCommand('copy'); again, then copy to the clipboard, as I want to check the list of copies in my windows. 
The two are different and existing simultaneously, we are not trying to use the chrome storage API to copy to the clipboard.

The second function is that the text that I will paste is from the container which stores the selected text I copied, we do not visit the windows clipboard anymore. 
And the popup will show when the input box is focused on.

As I said, there are no similar extensions support popup , and the function is as the [MultiCopy Clipboard, Copy & Paste](https://chrome.google.com/webstore/detail/multicopy-clipboard-copy/fahoojlhneomlloahghepkcegggkpahh?utm_source=chrome-ntp-icon) by pupup, and the result likes the Popcilp for Mac in the following photo.

![](https://pilotmoon.com/popclip/images/Mainshot-en.png)

**Comment by Pitmairen** [comment]
Ok, see what you mean now. I have to think about if this is something I want to include in selection search. It's not really a search feature, so it may be a better fit for new separate extension.

Selection search already has quite a lot of options and features, so I'm not sure I want to include even more features not really related to searching.

**Comment by lyscop** [comment]
Dear @Pitmairen ,

Aha, thank you so so so much to you to notice it again and willing to take time to take it to consideration.

Everything is all OK, but popup for click to store the selected text is much important.

It may take you some time or sprite to finish it, and I am looking forward to seeing it.

Best.

**Comment by lyscop** [comment]
@Pitmairen
I find a Javascript in Tampermonkey, it accomplishes double right-click to paste the words from storage which get the words from the clipboard, may this be helpful.

[double right-click to paste]https://greasyfork.org/zh-CN/scripts/401732-%E5%8F%8C%E5%87%BB%E5%8F%B3%E9%94%AE%E7%B2%98%E8%B4%B4/code)
