### ISSUE TITLE
Search engines disappeared

### ISSUE THREAD

**Issue by nightkall** [Pitmairen/selection-search#88]
All my search engines and settings are gone. When I try to import a backup the default search engines disappear too and I can't add any, only reinstalling the extension.

Chrome 81.0.4044.138 64bits

**Comment by Pitmairen** [comment]
Do you see any error messages if you open chrome extensions page (chrome://extensions/), enable developer mode in upper right corner,  find selection search in the extension list and click inspect view background/background.html, click the console tab in the window that opens. 

If something is crashin,  some error messages should be shown in the console.

**Comment by nightkall** [comment]
Today it's working again. In developer mode I get several errors like this:
`favicons:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
s2.googleusercontent.com/s2/favicons?domain_url=http://google.com#1590692287233:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
`
but I think it's related to favicons.

**Comment by Pitmairen** [comment]
Yes, those error shouldn't cause any problems, it's just some favicons that have failed to load. 

It could be something with the sync storage. If enabled, the data is automatically synced and stored somewhere by chrome. If something was temporary wrong with the sync storage, it could maybe cause your settings to disappear.  

Do you have multiple browsers on different computers, with sync enabled? If so, and something was wrong with one of the browser it could maybe sync bad data to the other browsers, but I have not seen that happen before.

**Comment by nightkall** [comment]
Sorry for the late reply. I only have one computer with Chrome sync. Maybe a forced shutdown corrupted the data in some way, I don't know. Now it's working fine without any issue. Thanks for your time.

**Comment by Pitmairen** [comment]
Ok, I will assume it was just some kind of random error. Hopefully it it not a common problem.
