### ISSUE TITLE
Using any "styling" yields this....

### ISSUE THREAD

**Issue by ghost** [Pitmairen/selection-search#9]
![untitled](https://cloud.githubusercontent.com/assets/8393129/7775674/7ae128fc-00b5-11e5-8170-88bc91f6a5c2.png)
After a certain length, all search engines' icons/names disappears.
and sub-folders stop working too.

**Comment by Pitmairen** [comment]
It's a stupid mistake in the code. I will fix it soon.

**Comment by Pitmairen** [comment]
It should be working in version 0.8.4.

I also needed to change the css a little and added a "mainmenu" and "submenu" class to the popup html. So custom styling may need to be updated.

**Comment by Droyk** [comment]
just checked it ..it is fixed too so plz close this issue down
