### ISSUE TITLE
Search with multiple engines

### ISSUE THREAD

**Issue by Rogroom** [Pitmairen/selection-search#92]
Thanks for the great search add-on, but it won't be perfect unless multiple engines search is added to functions.
Currently separators and submenus are used to make distinctive groups of search engines. It would be logical to open group of search engines (in multiple tabs) by clicking on a submenu name or separator.

**Comment by Pitmairen** [comment]
Hi, this should already be available. If you click the wrench next to the submenu there should be an option "Open all on click". When the is enabled, all search engines in the submenu should open in separate tabs when the submenu is clicked.

**Comment by Rogroom** [comment]
Wow!! Even more options than I could imagine. Thanks a lot!
