### ISSUE TITLE
In Emby page doesn't work well

### ISSUE THREAD

**Issue by simonbcn** [Pitmairen/selection-search#94]
```
Google Chrome 84.0.4147.89 
Selection Search 0.8.56
```

When I select something like this (_see image and text_), it doesn't show the popup icon: 
```
Los miserables

```
![captura_20200720_153644](https://user-images.githubusercontent.com/428231/87943821-dbd47980-ca9e-11ea-8088-b2ca022eabbe.png)

When selecting there is an end space that is not really a space, it is a "line feed" (_ASCII code: 010_). 
In order for the menu icon to appear I have to correct the selection so as not to include that final "space".

**Comment by Pitmairen** [comment]
There is an option "Allow newline / linebreak in selection" that should make the search work with newline in the selection. You find it at the bottom of the options page, under "Other Options".

**Comment by simonbcn** [comment]
Yes, it was that. Thanks.
